/**
 * Generates seed-users.sql (hashed, safe to commit nowhere) and users.csv (the
 * plain passwords — hand these out, then delete the file).
 *
 *   node scripts/create-users.mjs                 25 admins, 0 employees
 *   node scripts/create-users.mjs 25 10           25 admins, 10 employees
 *
 * Hashing matches the Worker exactly: PBKDF2-SHA256, 100000 iterations, 32 bytes.
 */
import { pbkdf2Sync, randomBytes } from 'node:crypto';
import { writeFileSync } from 'node:fs';

const adminCount = Number(process.argv[2] || 25);
const empCount = Number(process.argv[3] || 0);

const hash = (password) => {
  const salt = randomBytes(16).toString('hex');
  const digest = pbkdf2Sync(password, Buffer.from(salt, 'hex'), 100000, 32, 'sha256').toString('hex');
  return `pbkdf2$100000$${salt}$${digest}`;
};

// Readable passwords: no look-alike characters.
const ALPHABET = 'abcdefghjkmnpqrstuvwxyz23456789';
const password = () => Array.from(randomBytes(10)).map((b) => ALPHABET[b % ALPHABET.length]).join('');

const sql = ['-- Generated by scripts/create-users.mjs. Run once, then delete users.csv.'];
const csv = ['role,username,password,name'];

const add = (role, username, name) => {
  const pw = password();
  sql.push(
    `INSERT INTO users (username, password_hash, role, name) VALUES ` +
    `('${username}', '${hash(pw)}', '${role}', '${name.replace(/'/g, "''")}');`,
  );
  csv.push(`${role},${username},${pw},${name}`);
};

for (let i = 1; i <= adminCount; i++) {
  const n = String(i).padStart(2, '0');
  add('admin', `admin${n}`, `Admin ${n}`);
}
for (let i = 1; i <= empCount; i++) {
  const n = String(i).padStart(2, '0');
  add('employee', `emp${n}`, `Employee ${n}`);
}

writeFileSync(new URL('../seed-users.sql', import.meta.url), sql.join('\n') + '\n');
writeFileSync(new URL('../users.csv', import.meta.url), csv.join('\n') + '\n');
console.log(`Wrote seed-users.sql and users.csv — ${adminCount} admins, ${empCount} employees.`);
